### PR TITLE
cmd/root: Retry `skopeo` and `podman pull` commands

### PR DESCRIPTION
**Pull request by jlebon**
Add a new `RunExt` command and then use it to retry the `skopeo` and `podman pull` commands. See individual commit messages for details.

### CODE REVIEW

**Comment by jlebon** [comment]
Going to hold this for now while I test it through the MCD too instead of directly.
/hold

**Comment by jlebon** [comment]
OK, tested working! I dropped the retries in the MCD here: https://github.com/openshift/machine-config-operator/pull/336.
/hold cancel

**Comment by cgwalters** [comment]
LGTM

**Pull request merged**
